data = read.delim("./household_power_consumption.txt", sep=";", na.strings="?")
data$datetime = strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
data$Date = as.Date(data$Date, "%d/%m/%Y")
beginDate = as.Date("2007-02-01")
endDate = as.Date("2007-02-02")
data = data[(data$Date >= beginDate) & (data$Date <= endDate), ]
plot(data$datetime, data$Sub_metering_1, xlab="", ylab="Energy sub metering", col="black", type="l")
lines(data$datetime, data$Sub_metering_2, col="red")
lines(data$datetime, data$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
dev.copy(png, "plot3.png")
dev.off()